---
- hosts: all
  become: true
  become_user: root

  pre_tasks:
    - name: Download the MySQL repo.
      get_url:
        url: http://10.151.137.13:8083/mysql/mysqlrepo/{{ mysql_repo }}
        dest: /etc/yum.repos.d/
        validate_certs: no
      when: ansible_os_family == "RedHat"
    
    - name: yum clean all
      shell: yum clean all && yum makecache

    - name: Override variables for MySQL (RedHat).
      set_fact:
        mysql_log_error: /var/log/mysqld.err
        mysql_syslog_tag: mysqld
        mysql_pid_file: /var/run/mysqld/mysqld.pid
        mysql_socket: /var/lib/mysql/mysql.sock
      when: ansible_os_family == "RedHat"

  roles:
    - role: geerlingguy.mysql
