---
- hosts: 10.151.137.40
  pre_tasks:
  - name:
    set_fact:
      jump_host: "{{ lookup('env', 'JMS_SERVER') }}"
      jump_username: "{{ lookup('env', 'JMS_USERNAME') }}"
      jump_password: "{{ lookup('env', 'JMS_PASSWORD') }}"
      jump_database: "{{ lookup('env', 'JMS_DATABASE') }}"
      forever_key: "{{ lookup('env', 'TOKEN') }}"
      tower_user: "{{ lookup('env', 'TOWER_USERNAME') }}"
      tower_pass: "{{ lookup('env', 'TOWER_PASSWORD') }}"
      
  
  tasks:
    #- name: show result
    #  debug: msg="{{ jump_username }},{{ jump_host }},{{ jump_password }}"
    - name: "同步credential"
      script: /opt/test.py "{{ jump_host }}" "{{ jump_username }}" "{{ jump_password }}" "{{ jump_database }}"  "{{ forever_key }}"  "{{ tower_user }}" "{{ tower_pass }}"
      args:
        executable: python3
             
      