---
# author: lework

- name: install_from_rpm | Download the php repo.
  get_url: "url={{ php_rpm_url }} dest=/etc/yum.repos.d validate_certs=no"
    
- name: install_from_rpm | Ensure PHP packages are installed.
  yum: "name={{ item }} state=installed update_cache=yes"
  with_items: "{{ php_rpm }}"
