---
# author: lework

software_files_path: "/opt"
software_install_path: "/data/zabbix"

zabbix_agent_version: "3.0.3"

zabbix_agent_file: "zabbix-{{ zabbix_agent_version }}.tar.gz"
zabbix_agent_file_path: "{{ software_files_path }}/{{ zabbix_agent_file }}"
zabbix_agent_file_url: "http://10.151.137.6/zabbix/{{ zabbix_agent_file }}"
hdware_file_url: "http://10.151.137.6/zabbix/hdware.sh"

zabbix_agent_packages:
  - "zabbix-agent-{{ zabbix_agent_version }}"

zabbix_agent_user: zabbix
zabbix_agent_group: zabbix

zabbix_agent_install_from_source: false

zabbix_agent_source_dir: "/tmp/{{ zabbix_agent_file | replace('.tar.gz','') }}"
zabbix_agent_source_configure_command: >
  ./configure
  --prefix={{ software_install_path }}
  --enable-agent
zabbix_agent_conf_path: "/etc/zabbix" 
zabbix_agent_logs_path: "/var/log/zabbix"

zabbix_agent_hostname: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
zabbix_agent_server_host: "127.0.0.1"
